# Generated by Django 4.2 on 2025-01-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_companyinfo_termsofservice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyInfo",
        ),
        migrations.DeleteModel(
            name="TermsOfService",
        ),
    ]
